version: '3.9'

networks:
  local:

services:

  # Quarkus application
  hospital:
    container_name: "hospital"
    image: serrodcal/hospital:1.0.0-native-distroless
    ports: 
      - "8080:8080"
    networks:
      - local

  # Quarkus application
  doctor:
    container_name: "doctor"
    image: serrodcal/doctor:1.0.0-native-distroless
    environment:
      - QUARKUS_HTTP_PORT=8081
    ports: 
      - "8081:8081"
    networks:
      - local

  micro-integrator:
    container_name: "micro-integrator"
    image: wso2/wso2mi:4.1.0
    volumes:
      - ./config/micro-integrator/api/Health.xml:/home/wso2carbon/wso2mi-4.1.0/repository/deployment/server/synapse-configs/default/api/Health.xml
    ports: 
      - "8290:8290" # HTTP
      - "9201:9201" # Metrics
      - "9010:9010" # JMX
    networks:
      - local
    depends_on:
      - doctor
      - hospital